spring.application.name=ai-service
server.port=8086

farm.service.url=http://localhost:8082
crop.service.url=http://localhost:8083
weather.service.url=http://localhost:8084
user.service.url=http://localhost:8081

python.ai.url=http://localhost:5000